name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [12.x, 14.x, 15.x]
        os: [ubuntu-latest, macos-latest]
        experimental: [false]
        include:
        - os: windows-latest
          experimental: true
          node: 12.x
        - os: windows-latest
          experimental: true
          node: 14.x
        - os: windows-latest
          experimental: true
          node: 15.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - name: Environment Information
        run: npx envinfo
      - name: Run Test
        run: npm test

  release:
    name: release
    needs: test
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          check-latest: true
      - run: npm install
      - run: npx -p semantic-release@17 -p @evanlucas/semrel semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          GIT_AUTHOR_NAME: 'A simple bot'
          GIT_AUTHOR_EMAIL: 'simplesaurus@evanlucas.com'
          GIT_COMMITTER_NAME: 'A simple bot'
          GIT_COMMITTER_EMAIL: 'simplesaurus@evanlucas.com'
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

